/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henry
 */
public class FrmZodiac extends javax.swing.JFrame {

    /**
     * Creates new form FrmZodiac
     */
    public FrmZodiac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtZodiac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JTextArea();
        txtBulan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tanggal");

        jLabel2.setText("Bulan");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        jLabel3.setText("Zodiac");

        txtDes.setColumns(20);
        txtDes.setRows(5);
        jScrollPane1.setViewportView(txtDes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtZodiac))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProses)
                    .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        int tanggal = Integer.valueOf(txtTanggal.getText());
        int bulan = Integer.valueOf(txtBulan.getText());
        if (tanggal>=21 && bulan==3 || tanggal<=20 && bulan==4)
		{
			txtZodiac.setText("Aries(21 Maret - 20 April)");
                        txtDes.setText("Sifat Umum : suka menonjolkan diri, senang beraktifitas, menyukai kepemimpinan.");
		}
		else if(tanggal>=21 && bulan==4 || tanggal<=20 && bulan==5)
		{
			txtZodiac.setText("Taurus (21 April - Mei 20)");
                        txtDes.setText("Sifat Umum : suka hak milik dan tanah, menyukai kesenangan fisik.");
		}
		else if(tanggal>=21 && bulan==5 || tanggal<=20 && bulan==6)
		{
			txtZodiac.setText("Gemini (21 Mei - 20 Jun)");
                        txtDes.setText("Sifat Umum : menjadi penjual jasa atau ide, senang komunikasi dan masalah kesusastraan.");
		}
		else if(tanggal>=21 && bulan==6 || tanggal<=22 && bulan==7)
		{
			txtZodiac.setText("Cancer(21 Jun - 22 Jul)");
                        txtDes.setText("Sifat Umum : sangat peduli dalam urusan rumah dan keluarga, senang mengumpulkan benda berharga, sentimentil.");
		}
		else if(tanggal>=23 && bulan==7 || tanggal<=22 && bulan==8)
		{
			txtZodiac.setText("Leo(23 Jul - 22 Aug)");
                        txtDes.setText("Sifat Umum : suka mengatur dan memerintah, menyukai media dan usaha kreatif, mengorganisir yang lain.");
		}
		else if(tanggal>=23 && bulan==8|| tanggal<=22 && bulan==9)
		{
			txtZodiac.setText("Virgo(23 Aug - 22 Sep)");
                        txtDes.setText("Sifat Umum : bekerja cepat dan tepat, sehat dan higienis, suka menganalisa yang lain.");
		}
		else if(tanggal>=23 && bulan==9 || tanggal<=22 && bulan==10)
		{
			txtZodiac.setText("Libra(23 Sep - 22 Oct)");
                        txtDes.setText("Sifat Umum : menyenangi ide estetika, dalam seni dan lingkungan kerja yang berorientasi kemasyarakatan, adil pada siapa saja");
		}
		else if(tanggal>=23 && bulan==10 || tanggal<=22 && bulan==11)
		{
			txtZodiac.setText("Scorpio(23 Oct - 22 Nov)");
                        txtDes.setText("Sifat Umum : penuh misteri atau rahasia, menyukai problema dan riset.");
		}
		else if(tanggal>=23 && bulan==11 || tanggal<=21 && bulan==12)
		{
			txtZodiac.setText("Sagitarius(23 Nov - 21 Dec)");
                        txtDes.setText("Sifat Umum : pengembara, mengejar filsafat, menyukai penelitian.");
		}
		else if(tanggal>=22 && bulan==12 || tanggal<=19 && bulan==1)
		{
			txtZodiac.setText("Capicorn(22 Dec - 19 Jan)");
                        txtDes.setText("Sifat Umum : mengejar keuntungan bisnis (fiansial) dan status social.");
		}
		else if(tanggal>=20 && bulan==1 || tanggal<=19 && bulan==2)
		{
			txtZodiac.setText("Aquarius(20 Jan - 19 Feb)");
                        txtDes.setText("Sifat Umum : mengejar segi kemanusiaan dan pengetahuan, menyukai aktifitas kelompok.");
		}
		else if(tanggal>=20 && bulan==2 || tanggal<=20 && bulan==3)
		{
			txtZodiac.setText("Pices(20 Feb - 20 Mar)");
                        txtDes.setText("Sifat Umum : menyukai hal-hal spiritual, kesenian dan lautan.");
		}
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmZodiac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBulan;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtZodiac;
    // End of variables declaration//GEN-END:variables
}
